import { Inter } from "next/font/google";
import styles from "./style.home.css";
import Header from "../components/Header";
import Footer from "../components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Education-CZ",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (    
      <>
        <Header variant='public' />
        {children}
        <Footer />
      </>    
  );
}
